---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/6 9:19
---
--for var =8,1,-3 do
--    print(var)
--end
--a=6
--if (a>0) then
--    a=a-1
--    print(a)
--elseif (a<0) then
--    a=a-1
--    print(a)
--end
--a =3
--b= 5
--function myfun(a,b)
--    if (a>b) then
--        print(a)
--    else
--        print(b)
--    end
--end
--myfun(7,9)
--a=true
--b=true
--if (a and b) then
--    print("a and b 条件为真")
--else
--    print("a and b条件为假")
--end
local tab ={3,16,7,2,77,4,6}
--print("tab的第三个数字",tab[3])
--print(tab[2])
--print("tab的长度",#tab)
--tab[8] =11
--table.insert(tab,11)//和作用一样，同上
--tab[#tab+1] = 11
--print("tab的第8个数字",tab[8])
--删除
--tab[7] = nil;
--print("第七个数字",tab[7])
--print("删除后长度",#tab)

--迭代器
--for k,v in pairs(tab) do
--    print("第"..k.."个数为"..v)
--end






