---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/5/6 10:33
---

--自定义key，key不算table的长度
--local ll = {
--    name = "小鱼",
--    grade = "55",
--    blood = "100",
--    blueglaze = "100",
--    online = "false",
--    personal = "大家好，我是小鱼";
--};
--if 角色信息.是否在线 then
--    print("小鱼在线")
--else
--    print("小鱼下线了")
--end
--会访问自定义的键位值
--for k,v in pairs(ll) do
--    print(k..":"..v)
--end

local ll= {
    name = "小鱼",
    grade = "55",
    blood = "100",
    blueglaze = "100",
    online = "false",
    personal = "大家好，我是小鱼";
};
for k,v in ipairs(ll) do
    print(k..":"..v)
end