---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/6/2 11:06
---

--s = "hello world from Lua"
--for w in string.gmatch(s, "%a+") do
--    print(w)
--end



--t = {}
--s = "from=world, to=Lua"
--for k, v in string.gmatch(s, "(%w+)=(%w+)") do
--    t[k] = v
--    print(k)
--    print(v)
--end


--print(string.sub(str, 3,5))
--print(str)


function StrToStringArray(str)
    local result = {}
    for k =1 ,#str do
        table.insert(result,k,string.sub(str,k,k))
    end
    print("连接后的字符串 ",table.concat(result,", "))
    local tables = {}
    tables["num"] = bit32.lshift(result[4], 8) + result[5]--
end
--str = "123456789"

str = "0101825803FBF560DF60B5574300009D0300FFB10000007000000000383938363034323832323139433031303038353038363135363630343235303738353300000000003436303034343832373030303835300000000000424332364E4352303141303800000000000000000000000000000000002F006000030061000100630000000000150064006100020062000000000017000000610003006200000000001800000F"
StrToStringArray(str)

--print(#string);

