---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/4/28 14:22
---

--a=1 b=2
--
--a,b =b,a
--print(a,b)

--for i=1,f(x) do
--    print(i)
--end

--for i=10,1,-1 do
--    print(i)
--end
--function f(x)
--    print("function")
--    return x*2
--end
--for i=1,f(5) do print(i)
--end

--days = {"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"}
--for i,v in ipairs(days) do  print(v) end
