---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/4/30 9:37
---

local MainScene = class("MainScene", function()
    return display.newScene("MainScene")
end)

function MainScene:ctor()
    cc.ui.UILabel.new({
        UILabelType = 2, text = "北方有佳人。绝世而独立。", size = 18 })
      :align(display.CENTER, display.cx, display.cy)
      :addTo(self)
end

function MainScene:onEnter()
end