---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/4/29 9:08
---
--myprint = function(param)
--    print("这是打印函数 -   ##",param,"##")
--end
--
--function add(num1,num2,functionPrint)
--    result = num1 + num2
--    -- 调用传递的函数参数,调用
--    functionPrint(result)
--end
--myprint(10)
---- myprint 函数作为参数传递
--add(2,5,myprint)

--function maximum (a)
--    local mi = 1             -- 最大值索引
--    local m = a[mi]          -- 最大值
--    for i,val in ipairs(a) do
--        if val > m then
--            mi = i
--            m = val
--        end
--    end
--    return m, mi
--end
--
--print(maximum({8,10,23,12,5}))

function maxnum(a)
    local b = 1
    local c = a[b]
    for x,y in ipairs(a) do
        if y>c then
            b=x c=y
        end
end
    print(b,c);
    return b,c
end

maxnum({1,3,6,8,4,0})

--print(maxnum({1,3,6,8,4,0}))
--print("hhhh")